name: Run Integration Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.x"

      - name: Restore cached part 1
        id: restore-cache-p1
        uses: actions/cache@v2
        with:
          path: archive/part1-archive.7z
          key: ${{ runner.os }}-part-1

      - name: Restore cached part 2
        id: restore-cache-p2
        uses: actions/cache@v2
        with:
          path: archive/part2-archive.7z
          key: ${{ runner.os }}-part-2

      - name: Download the archive part 1
        if: steps.restore-cache-p1.outputs.cache-hit != 'true'
        run: wget http://eliot-jones.com:8081/part1-archive.7z -nv -P archive/ && ls archive

      - name: Download the archive part 2
        if: steps.restore-cache-p2.outputs.cache-hit != 'true'
        run: wget http://eliot-jones.com:8081/part2-archive.7z -nv -P archive/ && ls archive

      - name: Print output size part 1
        run: stat --printf="%s" archive/part1-archive.7z

      - name: Print output size part 2
        run: stat --printf="%s" archive/part2-archive.7z

      - name: Unzip archives
        run: sudo apt-get install p7zip-full && cd archive && 7z x part1-archive.7z && 7z x part2-archive.7z

      - name: List Unzipped
        run: ls archive