name: Run Integration Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.1.x"

      - name: Restore cached part 2
        id: restore-cache-p2
        uses: actions/cache@v2
        with:
          path: archive/part2-archive.7z
          key: ${{ runner.os }}-part-2

      - name: Download the archive
        if: steps.restore-cache-p2.outputs.cache-hit != 'true'
        run: mkdir archive && wget http://eliot-jones.com:8081/part2-archive.7z -nv -P archive/ && ls archive

      - name: Print output size
        run: stat --printf="%s" archive/part2-archive.7z